name: dateline
description: "A new Flutter package project for scrollable date picking."
version: 0.0.1
homepage: https://github.com/Pavel401/scrollable_date_picker

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  scrollable_positioned_list: ^0.3.8
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

topics:
  - date-picker
  - date-range-picker
  - scrollable-date-picker
  - flutter-date-picker
  - flutter-scrollable-date-picker

platforms:
  android:
  ios:

screenshots:
  - description: "The Scrollable Date Picker"
    path: example/images/1.png

license: MIT
